

export default [
        {
        label:'账号管理',
        to:'',
        children:[
                        {
                label:'管理员账号列表',
                to:'/admin/admins',
            },

            {
                label:'修改管理员密码',
                to:'/admin/mod',
            },

                        {
                label:'添加管理员账号',
                to:'/admin/adminsadd',
            },
                        {
                label:'用户账号管理',
                to:'/admin/yonghu',
            },
                        {
                label:'添加新用户',
                to:'/admin/yonghuadd',
            },

                    ]
    },
        {
        label:'地区管理',
        to:'',
        children:[
                        {
                label:'添加新地区',
                to:'/admin/diquadd',
            },
                        {
                label:'查询地区',
                to:'/admin/diqu',
            },
                    ]
    },
        {
        label:'景点管理',
        to:'',
        children:[
            {
                label:'查询景点',
                to:'/admin/jingdianxinxi',
            },
                        {
                label:'添加景点',
                to:'/admin/jingdianxinxiadd',
            },

                    ]
    },
        {
        label:'美食管理',
        to:'',
        children:[
                        {
                label:'添加美食类别',
                to:'/admin/meishifenleiadd',
            },
                        {
                label:'查询美食类别',
                to:'/admin/meishifenlei',
            },
                        {
                label:'添加美食',
                to:'/admin/difangmeishiadd',
            },
                        {
                label:'查询美食',
                to:'/admin/difangmeishi',
            },
                    ]
    },
        {
        label:'线路管理',
        to:'',
        children:[
                        {
                label:'添加线路',
                to:'/admin/lvyouxianluadd',
            },
                        {
                label:'查询线路',
                to:'/admin/lvyouxianlu',
            },
                    ]
    },
        {
        label:'订单管理',
        to:'',
        children:[
                        {
                label:'查询订单',
                to:'/admin/yuding',
            },
                    ]
    },
        {
        label:'新闻管理',
        to:'',
        children:[
                        {
                label:'添加新闻类别',
                to:'/admin/xinwenfenleiadd',
            },
                        {
                label:'查询新闻类别',
                to:'/admin/xinwenfenlei',
            },
                        {
                label:'添加新闻',
                to:'/admin/xinwenxinxiadd',
            },
                        {
                label:'查询新闻',
                to:'/admin/xinwenxinxi',
            },
                    ]
    },
        {
        label:'服务中心',
        to:'',
        children:[
                        {
                label:'添加友情链接',
                to:'/admin/youqinglianjieadd',
            },
                        {
                label:'查询友情链接',
                to:'/admin/youqinglianjie',
            },
                        {
                label:'添加轮播图',
                to:'/admin/lunbotuadd',
            },
                        {
                label:'查询轮播图',
                to:'/admin/lunbotu',
            },
                        {
                label:'留言板',
                to:'/admin/liuyanban',
            },
                    ]
    },
    ]
